spring:
  application:
    name: gateway
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: service-1
              uri: lb://service-1
              predicates:
                - Path=/service-1/**
            # - id: service-2
            #   uri: lb://service-2
            #   predicates:
            #     - Path=/service-2/**
            # - id: service-3
            #   uri: lb://service-3
            #   predicates:
            #     - Path=/service-3/**
